-- Corrección completa de puestos
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Director General') WHERE codigo_empleado = 'AGV0002';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Recepcion, Materiales y Despachos a Maquilas') WHERE codigo_empleado = 'AGV0010';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Ganader�a') WHERE codigo_empleado = 'AGV0018';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Producto Terminado, Distribucion y Transporte') WHERE codigo_empleado = 'AGV0034';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Administraci�n') WHERE codigo_empleado = 'AGV0065';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Director de Finanzas y Tecnologias de la Informacion') WHERE codigo_empleado = 'AGV0076';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Control de Procesos') WHERE codigo_empleado = 'AGV0083';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Directora de Investigacion y Desarrollo') WHERE codigo_empleado = 'AGV0111';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Limpieza Y Mantenimiento') WHERE codigo_empleado = 'AGV0124';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Directora de Desarrollo Organizacional') WHERE codigo_empleado = 'AGV0125';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Subgerente de Ventas Internacionales') WHERE codigo_empleado = 'AGV0187';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Logistica y Distribucion') WHERE codigo_empleado = 'AGV0240';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Ganader�a') WHERE codigo_empleado = 'AGV0246';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Materiales y Despacho Maquilas') WHERE codigo_empleado = 'AGV0265';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asesor') WHERE codigo_empleado = 'AGV0267';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Materiales y Despacho Maquilas') WHERE codigo_empleado = 'AGV0298';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente Administrativo de Ventas Internacionales') WHERE codigo_empleado = 'AGV0315';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Coordinador de Proyectos de Mejora de TI') WHERE codigo_empleado = 'AGV0319';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Subgerente de Estabilidades y Validaciones Analiticas') WHERE codigo_empleado = 'AGV0343';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Marketing') WHERE codigo_empleado = 'AGV0359';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Proyectos y Procesos Farmaceuticos') WHERE codigo_empleado = 'AGV0361';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Directora Comercial Local') WHERE codigo_empleado = 'AGV0362';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Producto Terminado y Distribucion') WHERE codigo_empleado = 'AGV0384';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe Tecnico Comercial Internacional Petmedica America Latina') WHERE codigo_empleado = 'AGV0397';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Produccion de Maquilas') WHERE codigo_empleado = 'AGV0404';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Abastecimiento') WHERE codigo_empleado = 'AGV0427';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Finanzas') WHERE codigo_empleado = 'AGV0442';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Control de Calidad MP') WHERE codigo_empleado = 'AGV0455';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Sanidad Aves y Cerdos') WHERE codigo_empleado = 'AGV0470';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor Contable') WHERE codigo_empleado = 'AGV0476';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Distribucion Internacional') WHERE codigo_empleado = 'AGV0524';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Compras Locales') WHERE codigo_empleado = 'AGV0563';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Back Office y Procedimientos Comerciales') WHERE codigo_empleado = 'AGV0572';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Asuntos Regulatorios Cuentas Claves') WHERE codigo_empleado = 'AGV0573';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Dise�o de Material de Empaque') WHERE codigo_empleado = 'AGV0603';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Innovacion y Desarrollo Farmaceutico') WHERE codigo_empleado = 'AGV0612';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Asuntos Regulatorios Latam') WHERE codigo_empleado = 'AGV0618';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Analista de Creditos y Cobranzas') WHERE codigo_empleado = 'AGV0619';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Chofer') WHERE codigo_empleado = 'AGV0620';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de CRM') WHERE codigo_empleado = 'AGV0628';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Validaciones Analiticas') WHERE codigo_empleado = 'AGV0630';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Escalonamiento y Transferencia') WHERE codigo_empleado = 'AGV0632';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Analista de Tesoreria') WHERE codigo_empleado = 'AGV0640';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Editor de Contenidos') WHERE codigo_empleado = 'AGV0650';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Distribucion Local') WHERE codigo_empleado = 'AGV0653';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Centro de Distribucion') WHERE codigo_empleado = 'AGV0662';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV0663';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Creditos y Cobranzas') WHERE codigo_empleado = 'AGV0668';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas - Animales de Compa��a') WHERE codigo_empleado = 'AGV0674';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asesor Legal') WHERE codigo_empleado = 'AGV0685';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Producto Terminado y Distribucion') WHERE codigo_empleado = 'AGV0690';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Talento Humano y SST') WHERE codigo_empleado = 'AGV0691';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Laboratorio') WHERE codigo_empleado = 'AGV0706';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Almacen') WHERE codigo_empleado = 'AGV0725';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Gestion de la Calidad') WHERE codigo_empleado = 'AGV0729';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV0749';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Creditos y Cobranzas') WHERE codigo_empleado = 'AGV0767';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Subgerente de Formulacion y Desarrollo de Procesos') WHERE codigo_empleado = 'AGV0771';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Sanidad- Animales Mayores y de Produccion') WHERE codigo_empleado = 'AGV0776';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asesor Externo de Investigaci�n en Ganado Lechero') WHERE codigo_empleado = 'AGV0779';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Guardian') WHERE codigo_empleado = 'AGV0780';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Subgerente de Desarrollo Analitico') WHERE codigo_empleado = 'AGV0786';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV0800';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Animales de Compa��a') WHERE codigo_empleado = 'AGV0801';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Formulaciones') WHERE codigo_empleado = 'AGV0802';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Estabilidades') WHERE codigo_empleado = 'AGV0823';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Mensajer�a de Investigaci�n Y Desarrollo') WHERE codigo_empleado = 'AGV0836';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Seguridad y Medio Ambiente') WHERE codigo_empleado = 'AGV0850';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV0852';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe Tecnico Comercial') WHERE codigo_empleado = 'AGV0856';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Ventas') WHERE codigo_empleado = 'AGV0859';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Control de Calidad') WHERE codigo_empleado = 'AGV0866';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Marketing Internacional') WHERE codigo_empleado = 'AGV0867';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o de Material de Empaque') WHERE codigo_empleado = 'AGV0868';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV0872';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Ventas Internacionales') WHERE codigo_empleado = 'AGV0878';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas - Nutriscience') WHERE codigo_empleado = 'AGV0881';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Ganaderia Zona Sur Oriente') WHERE codigo_empleado = 'AGV0884';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Operaciones') WHERE codigo_empleado = 'AGV0885';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Dispensacion') WHERE codigo_empleado = 'AGV0893';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Costos') WHERE codigo_empleado = 'AGV0896';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Comercio Exterior') WHERE codigo_empleado = 'AGV0898';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Planeamiento Financiero') WHERE codigo_empleado = 'AGV0905';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Subgerente de Ventas Locales') WHERE codigo_empleado = 'AGV0908';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Finanzas') WHERE codigo_empleado = 'AGV0914';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Sanidad - Animales Menores y Farmacovigilancia') WHERE codigo_empleado = 'AGV0915';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Ganaderia-Zona Norte') WHERE codigo_empleado = 'AGV0922';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Marketing') WHERE codigo_empleado = 'AGV0924';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Analista Contable') WHERE codigo_empleado = 'AGV0925';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor Senior de Tecnicas Analiticas') WHERE codigo_empleado = 'AGV0926';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Aplicaciones TI') WHERE codigo_empleado = 'AGV0931';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente Contable') WHERE codigo_empleado = 'AGV0934';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Administraci�n') WHERE codigo_empleado = 'AGV0935';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Analista Contable') WHERE codigo_empleado = 'AGV0939';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Talento Humano') WHERE codigo_empleado = 'AGV0946';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gestor de Contenido Digital Veterinario') WHERE codigo_empleado = 'AGV0949';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente Comercial Ganaderia') WHERE codigo_empleado = 'AGV0950';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Chofer') WHERE codigo_empleado = 'AGV0952';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Direcci�n de Investigaci�n y Desarrollo') WHERE codigo_empleado = 'AGV0953';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Tecnicas Analiticas') WHERE codigo_empleado = 'AGV0956';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Transformaci�n Digital') WHERE codigo_empleado = 'AGV0957';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Asuntos Regulatorios Latam') WHERE codigo_empleado = 'AGV0959';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Formulaciones') WHERE codigo_empleado = 'AGV0961';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Ventas Ecommerce') WHERE codigo_empleado = 'AGV0963';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Almacen e Inventarios') WHERE codigo_empleado = 'AGV0964';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV0965';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Comunicaci�n Interna') WHERE codigo_empleado = 'AGV0966';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV0967';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Procesos Industriales') WHERE codigo_empleado = 'AGV0968';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Formulaciones 2') WHERE codigo_empleado = 'AGV0970';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribucion de Materiales') WHERE codigo_empleado = 'AGV0973';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'KAM Aves y Cerdos Lima - Arequipa') WHERE codigo_empleado = 'AGV0976';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Costos') WHERE codigo_empleado = 'AGV0978';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV0979';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV0980';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Sanidad - Animales Menores y Farmacovigilancia') WHERE codigo_empleado = 'AGV0984';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Televentas') WHERE codigo_empleado = 'AGV0986';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Operaciones y Logistica') WHERE codigo_empleado = 'AGV0991';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Materiales') WHERE codigo_empleado = 'AGV0996';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Tesoreria') WHERE codigo_empleado = 'AGV0997';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas - Animales de Compa��a') WHERE codigo_empleado = 'AGV0999';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Ventas internacionales') WHERE codigo_empleado = 'AGV1001';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Materiales') WHERE codigo_empleado = 'AGV1002';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Estabilidades') WHERE codigo_empleado = 'AGV1008';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente de Producci�n') WHERE codigo_empleado = 'AGV1012';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Zona Centro') WHERE codigo_empleado = 'AGV1013';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1014';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Compras Locales') WHERE codigo_empleado = 'AGV1015';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas Ganaderia') WHERE codigo_empleado = 'AGV1018';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de TI') WHERE codigo_empleado = 'AGV1020';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1024';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Marketing Linea Nutricional') WHERE codigo_empleado = 'AGV1026';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Seguridad y Medio Ambiente') WHERE codigo_empleado = 'AGV1031';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de PT y Distribuci�n') WHERE codigo_empleado = 'AGV1033';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Planeamiento Y Control de La Producci�n') WHERE codigo_empleado = 'AGV1036';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1037';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Sanidad Animal') WHERE codigo_empleado = 'AGV1038';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Compras Internacionales') WHERE codigo_empleado = 'AGV1039';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1040';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Proyectos de Finanzas') WHERE codigo_empleado = 'AGV1042';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Infraestructura y Operaciones') WHERE codigo_empleado = 'AGV1044';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Infraestructura y Soporte TI') WHERE codigo_empleado = 'AGV1045';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Infraestructura y Soporte TI') WHERE codigo_empleado = 'AGV1046';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Formulaciones 3') WHERE codigo_empleado = 'AGV1048';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Sanidad - Animales Menores y Farmacovigilancia') WHERE codigo_empleado = 'AGV1049';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Validaciones Anal�ticas') WHERE codigo_empleado = 'AGV1050';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Desarrollo Analitico') WHERE codigo_empleado = 'AGV1052';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Atracci�n del Talento') WHERE codigo_empleado = 'AGV1053';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Propiedad Intelectual') WHERE codigo_empleado = 'AGV1054';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1058';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1062';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Operaciones de Producci�n') WHERE codigo_empleado = 'AGV1064';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Estabilidades') WHERE codigo_empleado = 'AGV1065';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Pet Nutriscience') WHERE codigo_empleado = 'AGV1068';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Pet Nutriscience') WHERE codigo_empleado = 'AGV1070';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Investigaci�n y Planeamiento de Demanda') WHERE codigo_empleado = 'AGV1071';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Recepci�n') WHERE codigo_empleado = 'AGV1073';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Infraestructura y TI - Part Time') WHERE codigo_empleado = 'AGV1074';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1075';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1076';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Ventas - Animales de Compa��a') WHERE codigo_empleado = 'AGV1077';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1079';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Desarrollo Anal�tico') WHERE codigo_empleado = 'AGV1081';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Control de Producci�n') WHERE codigo_empleado = 'AGV1082';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Aplicaciones') WHERE codigo_empleado = 'AGV1084';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Proyectos de TI') WHERE codigo_empleado = 'AGV1085';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Importaciones') WHERE codigo_empleado = 'AGV1089';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1091';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Facturaci�n') WHERE codigo_empleado = 'AGV1092';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o Gr�fico') WHERE codigo_empleado = 'AGV1093';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1094';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente T�cnico de Mantenimiento') WHERE codigo_empleado = 'AGV1095';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Control de Calidad') WHERE codigo_empleado = 'AGV1098';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Pet Nutriscience') WHERE codigo_empleado = 'AGV1100';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Pet Nutriscience') WHERE codigo_empleado = 'AGV1102';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Pet Nutriscience') WHERE codigo_empleado = 'AGV1103';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Exportaciones') WHERE codigo_empleado = 'AGV1105';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Formulaciones I') WHERE codigo_empleado = 'AGV1109';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Marketing') WHERE codigo_empleado = 'AGV1110';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o Gr�fico') WHERE codigo_empleado = 'AGV1111';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de PT y Distribuci�n') WHERE codigo_empleado = 'AGV1112';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Gerente Pet Nutriscience') WHERE codigo_empleado = 'AGV1116';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Marketing') WHERE codigo_empleado = 'AGV1118';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Dise�o') WHERE codigo_empleado = 'AGV1120';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Marketing - L�nea Ganader�a / Aves y Cerdos') WHERE codigo_empleado = 'AGV1121';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Sub Gerente T�cnico de Proyectos y Asesor Comercial') WHERE codigo_empleado = 'AGV1124';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Ventas Interpet') WHERE codigo_empleado = 'AGV1126';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Venta Interpet') WHERE codigo_empleado = 'AGV1127';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o Gr�fico') WHERE codigo_empleado = 'AGV1128';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Desarrollo Anal�tico') WHERE codigo_empleado = 'AGV1130';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Venta Interpet') WHERE codigo_empleado = 'AGV1132';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1133';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Dispensaci�n') WHERE codigo_empleado = 'AGV1134';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Limpieza y Lavado') WHERE codigo_empleado = 'AGV1135';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Estabilidades') WHERE codigo_empleado = 'AGV1136';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe de Planeamiento y Control de la Producci�n') WHERE codigo_empleado = 'AGV1137';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Ventas E-Commerce') WHERE codigo_empleado = 'AGV1138';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Materiales') WHERE codigo_empleado = 'AGV1139';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Desarrollo de Packaging') WHERE codigo_empleado = 'AGV1141';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Formulaciones') WHERE codigo_empleado = 'AGV1142';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Materiales') WHERE codigo_empleado = 'AGV1144';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Jefe T�cnico Ganader�a') WHERE codigo_empleado = 'AGV1145';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Marketing Internacional') WHERE codigo_empleado = 'AGV1146';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Seguridad y Medio Ambiente') WHERE codigo_empleado = 'AGV1147';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Chofer de Operaciones Log�sticas') WHERE codigo_empleado = 'AGV1148';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Trade Marketing Pets') WHERE codigo_empleado = 'AGV1149';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Desarrollo Online') WHERE codigo_empleado = 'AGV1152';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o de Material de Empaque - Compras') WHERE codigo_empleado = 'AGV1153';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Chofer') WHERE codigo_empleado = 'AGV1154';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1156';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Dise�o de Material de Empaque') WHERE codigo_empleado = 'AGV1158';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Promotor de Ventas Animales de Compa��a') WHERE codigo_empleado = 'AGV1159';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Estabilidades') WHERE codigo_empleado = 'AGV1161';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Auxiliar de Distribuci�n de Ventas E-Commerce') WHERE codigo_empleado = 'AGV1162';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Procesos Industriales') WHERE codigo_empleado = 'AGV1163';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Asuntos Regulatorios') WHERE codigo_empleado = 'AGV1164';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Representante de Venta Interpet') WHERE codigo_empleado = 'AGV1165';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Supervisor de Aseguramiento de la Calidad') WHERE codigo_empleado = 'AGV1166';
UPDATE empleados SET puesto_id = (SELECT id FROM puestos WHERE nombre = 'Asistente de Dise�o Gr�fico') WHERE codigo_empleado = 'AGV1167';