-- CARGAR PUESTOS
INSERT INTO puestos (nombre, area_id, nivel_jerarquico, activo) VALUES
  ('Director General', 18, 1, true),
  ('Supervisor de Recepcion, Materiales y Despachos a Maquilas', 2, 1, true),
  ('Jefe de Ventas Ganader´+¢a', 24, 1, true),
  ('Supervisor de Producto Terminado, Distribucion y Transporte', 2, 1, true),
  ('Jefe de Administraci´+¢n', 1, 1, true),
  ('Director de Finanzas y Tecnologias de la Informacion', 12, 1, true),
  ('Supervisor de Control de Procesos', 13, 1, true),
  ('Directora de Investigacion y Desarrollo', 19, 1, true),
  ('Auxiliar de Limpieza Y Mantenimiento', 1, 1, true),
  ('Directora de Desarrollo Organizacional', 4, 1, true),
  ('Subgerente de Ventas Internacionales', 35, 1, true),
  ('Gerente de Logistica y Distribucion', 3, 1, true),
  ('Asistente de Materiales y Despacho Maquilas', 2, 1, true),
  ('Asesor', 1, 1, true),
  ('Asistente Administrativo de Ventas Internacionales', 35, 1, true),
  ('Coordinador de Proyectos de Mejora de TI', 33, 1, true),
  ('Subgerente de Estabilidades y Validaciones Analiticas', 15, 1, true),
  ('Gerente de Marketing', 22, 1, true),
  ('Gerente de Proyectos y Procesos Farmaceuticos', 30, 1, true),
  ('Directora Comercial Local', 1, 1, true),
  ('Auxiliar de Producto Terminado y Distribucion', 2, 1, true),
  ('Jefe Tecnico Comercial Internacional Petmedica America Latina', 35, 1, true),
  ('Jefe de Produccion de Maquilas', 29, 1, true),
  ('Jefe de Abastecimiento', 10, 1, true),
  ('Supervisor de Finanzas', 16, 1, true),
  ('Asistente de Control de Calidad MP', 13, 1, true),
  ('Jefe de Sanidad Aves y Cerdos', 31, 1, true),
  ('Supervisor Contable', 11, 1, true),
  ('Asistente de Distribucion Internacional', 2, 1, true),
  ('Supervisor de Compras Locales', 10, 1, true),
  ('Jefe de Back Office y Procedimientos Comerciales', 1, 1, true),
  ('Jefe de Asuntos Regulatorios Cuentas Claves', 5, 1, true),
  ('Supervisor de Dise´+¢o de Material de Empaque', 5, 1, true),
  ('Gerente de Innovacion y Desarrollo Farmaceutico', 17, 1, true),
  ('Jefe de Asuntos Regulatorios Latam', 5, 1, true),
  ('Analista de Creditos y Cobranzas', 16, 1, true),
  ('Chofer', 1, 1, true),
  ('Jefe de CRM', 35, 1, true),
  ('Jefe de Validaciones Analiticas', 15, 1, true),
  ('Jefe de Escalonamiento y Transferencia', 17, 1, true),
  ('Analista de Tesoreria', 16, 1, true),
  ('Editor de Contenidos', 22, 1, true),
  ('Asistente de Distribucion Local', 2, 1, true),
  ('Jefe de Centro de Distribucion', 2, 1, true),
  ('Representante de Ventas Ganaderia', 24, 1, true),
  ('Supervisor de Creditos y Cobranzas', 16, 1, true),
  ('Representante de Ventas - Animales de Compa´+¢´+¢a', 1, 1, true),
  ('Asesor Legal', 16, 1, true),
  ('Gerente de Talento Humano y SST', 34, 1, true),
  ('Auxiliar de Laboratorio', 15, 1, true),
  ('Auxiliar de Almacen', 2, 1, true),
  ('Asistente de Gestion de la Calidad', 4, 1, true),
  ('Asistente de Creditos y Cobranzas', 16, 1, true),
  ('Subgerente de Formulacion y Desarrollo de Procesos', 17, 1, true),
  ('Jefe de Sanidad- Animales Mayores y de Produccion', 31, 1, true),
  ('Asesor Externo de Investigaci´+¢n en Ganado Lechero', 31, 1, true),
  ('Guardian', 31, 1, true),
  ('Subgerente de Desarrollo Analitico', 14, 1, true),
  ('Jefe de Asuntos Regulatorios', 5, 1, true),
  ('Gerente de Animales de Compa´+¢´+¢a', 1, 1, true),
  ('Jefe de Formulaciones', 17, 1, true),
  ('Jefe de Estabilidades', 15, 1, true),
  ('Auxiliar de Mensajer´+¢a de Investigaci´+¢n Y Desarrollo', 19, 1, true),
  ('Jefe de Seguridad y Medio Ambiente', 32, 1, true),
  ('Supervisor de Asuntos Regulatorios', 5, 1, true),
  ('Jefe Tecnico Comercial', 1, 1, true),
  ('Asistente de Ventas', 35, 1, true),
  ('Jefe de Control de Calidad', 13, 1, true),
  ('Jefe de Marketing Internacional', 35, 1, true),
  ('Asistente de Dise´+¢o de Material de Empaque', 5, 1, true),
  ('Supervisor de Ventas Internacionales', 35, 1, true),
  ('Representante de Ventas - Nutriscience', 26, 1, true),
  ('Jefe de Ventas Ganaderia Zona Sur Oriente', 24, 1, true),
  ('Supervisor de Operaciones', 29, 1, true),
  ('Supervisor de Dispensacion', 29, 1, true),
  ('Supervisor de Costos', 11, 1, true),
  ('Jefe de Comercio Exterior', 8, 1, true),
  ('Jefe de Planeamiento Financiero', 28, 1, true),
  ('Subgerente de Ventas Locales', 24, 1, true),
  ('Jefe de Finanzas', 16, 1, true),
  ('Jefe de Sanidad - Animales Menores y Farmacovigilancia', 31, 1, true),
  ('Jefe de Ventas Ganaderia-Zona Norte', 24, 1, true),
  ('Asistente de Marketing', 7, 1, true),
  ('Analista Contable', 11, 1, true),
  ('Supervisor Senior de Tecnicas Analiticas', 14, 1, true),
  ('Jefe de Aplicaciones TI', 33, 1, true),
  ('Asistente Contable', 11, 1, true),
  ('Asistente de Administraci´+¢n', 1, 1, true),
  ('Supervisor de Talento Humano', 34, 1, true),
