-- Ya se crearon 38 ├íreas

-- CREAR PUESTOS
INSERT INTO puestos (nombre, area_id, nivel_jerarquico, activo) VALUES
('Director General', 21, 1, true),
('Supervisor de Recepcion, Materiales y Despachos a Maquilas', 2, 1, true),
('Jefe de Ventas Ganader´┐¢a', 27, 1, true),
('Supervisor de Producto Terminado, Distribucion y Transporte', 2, 1, true),
('Jefe de Administraci´┐¢n', 1, 1, true),
('Director de Finanzas y Tecnologias de la Informacion', 13, 1, true),
('Supervisor de Control de Procesos', 14, 1, true),
('Directora de Investigacion y Desarrollo', 22, 1, true),
('Auxiliar de Limpieza Y Mantenimiento', 1, 1, true),
('Directora de Desarrollo Organizacional', 4, 1, true),
('Subgerente de Ventas Internacionales', 38, 1, true),
('Gerente de Logistica y Distribucion', 3, 1, true),
('Asistente de Materiales y Despacho Maquilas', 2, 1, true),
('Asesor', 1, 1, true),
('Asistente Administrativo de Ventas Internacionales', 38, 1, true),
('Coordinador de Proyectos de Mejora de TI', 36, 1, true),
('Subgerente de Estabilidades y Validaciones Analiticas', 16, 1, true),
('Gerente de Marketing', 25, 1, true),
('Gerente de Proyectos y Procesos Farmaceuticos', 33, 1, true),
('Directora Comercial Local', 26, 1, true),
('Auxiliar de Producto Terminado y Distribucion', 2, 1, true),
('Jefe Tecnico Comercial Internacional Petmedica America Latina', 38, 1, true),
('Jefe de Produccion de Maquilas', 32, 1, true),
('Jefe de Abastecimiento', 11, 1, true),
('Supervisor de Finanzas', 18, 1, true),
('Asistente de Control de Calidad MP', 14, 1, true),
('Jefe de Sanidad Aves y Cerdos', 34, 1, true),
('Supervisor Contable', 12, 1, true),
('Asistente de Distribucion Internacional', 2, 1, true),
('Supervisor de Compras Locales', 11, 1, true),
('Jefe de Back Office y Procedimientos Comerciales', 28, 1, true),
('Jefe de Asuntos Regulatorios Cuentas Claves', 5, 1, true),
('Supervisor de Dise´┐¢o de Material de Empaque', 5, 1, true),
('Gerente de Innovacion y Desarrollo Farmaceutico', 19, 1, true),
('Jefe de Asuntos Regulatorios Latam', 5, 1, true),
('Analista de Creditos y Cobranzas', 18, 1, true),
('Chofer', 1, 1, true),
('Jefe de CRM', 38, 1, true),
('Jefe de Validaciones Analiticas', 16, 1, true),
('Jefe de Escalonamiento y Transferencia', 19, 1, true),
('Analista de Tesoreria', 18, 1, true),
('Editor de Contenidos', 25, 1, true),
('Asistente de Distribucion Local', 2, 1, true),
('Jefe de Centro de Distribucion', 2, 1, true),
('Representante de Ventas Ganaderia', 27, 1, true),
('Supervisor de Creditos y Cobranzas', 18, 1, true),
('Representante de Ventas - Animales de Compa´┐¢´┐¢a', 9, 1, true),
('Asesor Legal', 18, 1, true),
('Gerente de Talento Humano y SST', 37, 1, true),
('Auxiliar de Laboratorio', 16, 1, true),
('Auxiliar de Almacen', 2, 1, true),
('Asistente de Gestion de la Calidad', 4, 1, true),
('Asistente de Creditos y Cobranzas', 18, 1, true),
('Subgerente de Formulacion y Desarrollo de Procesos', 19, 1, true),
('Jefe de Sanidad- Animales Mayores y de Produccion', 34, 1, true),
('Asesor Externo de Investigaci´┐¢n en Ganado Lechero', 34, 1, true),
('Guardian', 34, 1, true),
('Subgerente de Desarrollo Analitico', 15, 1, true),
('Jefe de Asuntos Regulatorios', 5, 1, true),
('Gerente de Animales de Compa´┐¢´┐¢a', 9, 1, true),
('Jefe de Formulaciones', 19, 1, true),
('Jefe de Estabilidades', 16, 1, true),
('Auxiliar de Mensajer´┐¢a de Investigaci´┐¢n Y Desarrollo', 22, 1, true),
('Jefe de Seguridad y Medio Ambiente', 35, 1, true),
('Supervisor de Asuntos Regulatorios', 5, 1, true),
('Jefe Tecnico Comercial', 9, 1, true),
('Asistente de Ventas', 38, 1, true),
('Jefe de Control de Calidad', 14, 1, true),
('Jefe de Marketing Internacional', 38, 1, true),
('Asistente de Dise´┐¢o de Material de Empaque', 5, 1, true),
('Supervisor de Ventas Internacionales', 38, 1, true),
('Representante de Ventas - Nutriscience', 29, 1, true),
('Jefe de Ventas Ganaderia Zona Sur Oriente', 27, 1, true),
('Supervisor de Operaciones', 32, 1, true),
('Supervisor de Dispensacion', 32, 1, true),
('Supervisor de Costos', 12, 1, true),
('Jefe de Comercio Exterior', 8, 1, true),
('Jefe de Planeamiento Financiero', 31, 1, true),
('Subgerente de Ventas Locales', 27, 1, true),
('Jefe de Finanzas', 18, 1, true),
('Jefe de Sanidad - Animales Menores y Farmacovigilancia', 34, 1, true),
('Jefe de Ventas Ganaderia-Zona Norte', 27, 1, true),
('Asistente de Marketing', 7, 1, true),
('Analista Contable', 12, 1, true),
('Supervisor Senior de Tecnicas Analiticas', 15, 1, true),
('Jefe de Aplicaciones TI', 36, 1, true),
('Asistente Contable', 12, 1, true),
('Asistente de Administraci´┐¢n', 1, 1, true),
('Supervisor de Talento Humano', 37, 1, true),
('Gestor de Contenido Digital Veterinario', 7, 1, true),
('Gerente Comercial Ganaderia', 27, 1, true),
('Supervisor de Direcci´┐¢n de Investigaci´┐¢n y Desarrollo', 22, 1, true),
('Supervisor de Tecnicas Analiticas', 15, 1, true),
('Gerente de Transformaci´┐¢n Digital', 36, 1, true),
('Supervisor de Asuntos Regulatorios Latam', 5, 1, true),
('Auxiliar de Formulaciones', 19, 1, true),
('Asistente de Ventas Ecommerce', 7, 1, true),
('Asistente de Almacen e Inventarios', 2, 1, true),
('Jefe de Comunicaci´┐¢n Interna', 37, 1, true),
('Supervisor de Procesos Industriales', 19, 1, true),
('Supervisor de Formulaciones 2', 19, 1, true),
('Auxiliar de Distribucion de Materiales', 2, 1, true),
('KAM Aves y Cerdos Lima - Arequipa', 6, 1, true),
('Asistente de Costos', 12, 1, true),
('Promotor de Ventas Animales de Compa´┐¢´┐¢a', 9, 1, true),
('Supervisor de Sanidad - Animales Menores y Farmacovigilancia', 34, 1, true),
('Asistente de Televentas', 28, 1, true),
('Asistente de Operaciones y Logistica', 30, 1, true),
('Auxiliar de Distribuci´┐¢n de Materiales', 2, 1, true),
('Asistente de Tesoreria', 18, 1, true),
('Asistente de Ventas internacionales', 38, 1, true),
('Supervisor de Estabilidades', 16, 1, true),
('Gerente de Producci´┐¢n', 32, 1, true),
('Jefe de Ventas Zona Centro', 27, 1, true),
('Asistente de Compras Locales', 11, 1, true),
('Supervisor de TI', 36, 1, true),
('Asistente de Asuntos Regulatorios', 5, 1, true),
('Supervisor de Marketing Linea Nutricional', 25, 1, true),
('Asistente de Seguridad y Medio Ambiente', 35, 1, true),
('Auxiliar de PT y Distribuci´┐¢n', 2, 1, true),
('Supervisor de Planeamiento Y Control de La Producci´┐¢n', 30, 1, true),
('Asistente de Sanidad Animal', 34, 1, true),
('Asistente de Compras Internacionales', 11, 1, true),
('Supervisor de Proyectos de Finanzas', 18, 1, true),
('Supervisor de Infraestructura y Operaciones', 36, 1, true),
('Asistente de Infraestructura y Soporte TI', 36, 1, true),
('Supervisor de Formulaciones 3', 19, 1, true),
('Asistente de Sanidad - Animales Menores y Farmacovigilancia', 34, 1, true),
('Supervisor de Validaciones Anal´┐¢ticas', 16, 1, true),
('Jefe de Desarrollo Analitico', 15, 1, true),
('Asistente de Atracci´┐¢n del Talento', 37, 1, true),
('Jefe de Propiedad Intelectual', 19, 1, true),
('Asistente de Operaciones de Producci´┐¢n', 32, 1, true),
('Promotor de Ventas Pet Nutriscience', 29, 1, true),
('Jefe de Investigaci´┐¢n y Planeamiento de Demanda', 28, 1, true),
('Auxiliar de Recepci´┐¢n', 2, 1, true),
('Auxiliar de Infraestructura y TI - Part Time', 36, 1, true),
('Supervisor de Desarrollo Anal´┐¢tico', 15, 1, true),
('Asistente de Control de Producci´┐¢n', 30, 1, true),
('Asistente de Aplicaciones', 36, 1, true),
('Jefe de Proyectos de TI', 36, 1, true),
('Asistente de Importaciones', 8, 1, true),
('Auxiliar de Facturaci´┐¢n', 18, 1, true),
('Asistente de Dise´┐¢o Gr´┐¢fico', 25, 1, true),
('Asistente T´┐¢cnico de Mantenimiento', 33, 1, true),
('Auxiliar de Control de Calidad', 14, 1, true),
('Asistente de Exportaciones', 8, 1, true),
('Supervisor de Formulaciones I', 19, 1, true),
('Jefe de Marketing', 24, 1, true),
('Gerente Pet Nutriscience', 29, 1, true),
('Supervisor de Dise´┐¢o', 25, 1, true),
('Supervisor de Marketing - L´┐¢nea Ganader´┐¢a / Aves y Cerdos', 25, 1, true),
('Sub Gerente T´┐¢cnico de Proyectos y Asesor Comercial', 33, 1, true),
('Jefe de Ventas Interpet', 23, 1, true),
('Representante de Venta Interpet', 23, 1, true),
('Asistente de Desarrollo Anal´┐¢tico', 15, 1, true),
('Auxiliar de Dispensaci´┐¢n', 32, 1, true),
('Auxiliar de Limpieza y Lavado', 15, 1, true),
('Jefe de Planeamiento y Control de la Producci´┐¢n', 30, 1, true),
('Auxiliar de Distribuci´┐¢n de Ventas E-Commerce', 2, 1, true),
('Supervisor de Desarrollo de Packaging', 19, 1, true),
('Jefe T´┐¢cnico Ganader´┐¢a', 27, 1, true),
('Asistente de Marketing Internacional', 38, 1, true),
('Chofer de Operaciones Log´┐¢sticas', 2, 1, true),
('Asistente de Trade Marketing Pets', 25, 1, true),
('Supervisor de Desarrollo Online', 7, 1, true),
('Asistente de Dise´┐¢o de Material de Empaque - Compras', 5, 1, true),
('Auxiliar de Dise´┐¢o de Material de Empaque', 5, 1, true),
('Asistente de Estabilidades', 17, 1, true),
('Supervisor de Aseguramiento de la Calidad', 4, 1, true);


-- RESUMEN:
-- ├üreas: 38
-- Puestos: 170
-- Empleados: 219
