  ('Gestor de Contenido Digital Veterinario', 7, 1, true),
  ('Gerente Comercial Ganaderia', 24, 1, true),
  ('Supervisor de Direcci´+¢n de Investigaci´+¢n y Desarrollo', 19, 1, true),
  ('Supervisor de Tecnicas Analiticas', 14, 1, true),
  ('Gerente de Transformaci´+¢n Digital', 33, 1, true),
  ('Supervisor de Asuntos Regulatorios Latam', 5, 1, true),
  ('Auxiliar de Formulaciones', 17, 1, true),
  ('Asistente de Ventas Ecommerce', 7, 1, true),
  ('Asistente de Almacen e Inventarios', 2, 1, true),
  ('Jefe de Comunicaci´+¢n Interna', 34, 1, true),
  ('Supervisor de Procesos Industriales', 17, 1, true),
  ('Supervisor de Formulaciones 2', 17, 1, true),
  ('Auxiliar de Distribucion de Materiales', 2, 1, true),
  ('KAM Aves y Cerdos Lima - Arequipa', 6, 1, true),
  ('Asistente de Costos', 11, 1, true),
  ('Promotor de Ventas Animales de Compa´+¢´+¢a', 1, 1, true),
  ('Supervisor de Sanidad - Animales Menores y Farmacovigilancia', 31, 1, true),
  ('Asistente de Televentas', 1, 1, true),
  ('Asistente de Operaciones y Logistica', 27, 1, true),
  ('Auxiliar de Distribuci´+¢n de Materiales', 2, 1, true),
  ('Asistente de Tesoreria', 16, 1, true),
  ('Asistente de Ventas internacionales', 35, 1, true),
  ('Supervisor de Estabilidades', 15, 1, true),
  ('Gerente de Producci´+¢n', 29, 1, true),
  ('Jefe de Ventas Zona Centro', 24, 1, true),
  ('Asistente de Compras Locales', 10, 1, true),
  ('Supervisor de TI', 33, 1, true),
  ('Asistente de Asuntos Regulatorios', 5, 1, true),
  ('Supervisor de Marketing Linea Nutricional', 22, 1, true),
  ('Asistente de Seguridad y Medio Ambiente', 32, 1, true),
  ('Auxiliar de PT y Distribuci´+¢n', 2, 1, true),
  ('Supervisor de Planeamiento Y Control de La Producci´+¢n', 27, 1, true),
  ('Asistente de Sanidad Animal', 31, 1, true),
  ('Asistente de Compras Internacionales', 10, 1, true),
  ('Supervisor de Proyectos de Finanzas', 16, 1, true),
  ('Supervisor de Infraestructura y Operaciones', 33, 1, true),
  ('Asistente de Infraestructura y Soporte TI', 33, 1, true),
  ('Supervisor de Formulaciones 3', 17, 1, true),
  ('Asistente de Sanidad - Animales Menores y Farmacovigilancia', 31, 1, true),
  ('Supervisor de Validaciones Anal´+¢ticas', 15, 1, true),
  ('Jefe de Desarrollo Analitico', 14, 1, true),
  ('Asistente de Atracci´+¢n del Talento', 34, 1, true),
  ('Jefe de Propiedad Intelectual', 17, 1, true),
  ('Asistente de Operaciones de Producci´+¢n', 29, 1, true),
  ('Promotor de Ventas Pet Nutriscience', 26, 1, true),
  ('Jefe de Investigaci´+¢n y Planeamiento de Demanda', 1, 1, true),
  ('Auxiliar de Recepci´+¢n', 2, 1, true),
  ('Auxiliar de Infraestructura y TI - Part Time', 33, 1, true),
  ('Supervisor de Desarrollo Anal´+¢tico', 14, 1, true),
  ('Asistente de Control de Producci´+¢n', 27, 1, true),
  ('Asistente de Aplicaciones', 33, 1, true),
  ('Jefe de Proyectos de TI', 33, 1, true),
  ('Asistente de Importaciones', 8, 1, true),
  ('Auxiliar de Facturaci´+¢n', 16, 1, true),
  ('Asistente de Dise´+¢o Gr´+¢fico', 22, 1, true),
  ('Asistente T´+¢cnico de Mantenimiento', 30, 1, true),
  ('Auxiliar de Control de Calidad', 13, 1, true),
  ('Asistente de Exportaciones', 8, 1, true),
  ('Supervisor de Formulaciones I', 17, 1, true),
  ('Jefe de Marketing', 21, 1, true),
  ('Gerente Pet Nutriscience', 26, 1, true),
  ('Supervisor de Dise´+¢o', 22, 1, true),
  ('Supervisor de Marketing - L´+¢nea Ganader´+¢a / Aves y Cerdos', 22, 1, true),
  ('Sub Gerente T´+¢cnico de Proyectos y Asesor Comercial', 30, 1, true),
  ('Jefe de Ventas Interpet', 20, 1, true),
  ('Representante de Venta Interpet', 20, 1, true),
  ('Asistente de Desarrollo Anal´+¢tico', 14, 1, true),
  ('Auxiliar de Dispensaci´+¢n', 29, 1, true),
  ('Auxiliar de Limpieza y Lavado', 14, 1, true),
  ('Jefe de Planeamiento y Control de la Producci´+¢n', 27, 1, true),
  ('Auxiliar de Distribuci´+¢n de Ventas E-Commerce', 2, 1, true),
  ('Supervisor de Desarrollo de Packaging', 17, 1, true),
  ('Jefe T´+¢cnico Ganader´+¢a', 24, 1, true),
  ('Asistente de Marketing Internacional', 35, 1, true),
  ('Chofer de Operaciones Log´+¢sticas', 2, 1, true),
  ('Asistente de Trade Marketing Pets', 22, 1, true),
  ('Supervisor de Desarrollo Online', 7, 1, true),
  ('Asistente de Dise´+¢o de Material de Empaque - Compras', 5, 1, true),
  ('Auxiliar de Dise´+¢o de Material de Empaque', 5, 1, true),
  ('Asistente de Estabilidades', 1, 1, true),
  ('Supervisor de Aseguramiento de la Calidad', 4, 1, true)
ON CONFLICT (nombre) DO NOTHING;

-- Total puestos: 170

